version: "3"

services:
  remixionnaire:
    build: ../
    restart: "unless-stopped"
    ports:
      - ${APP_PORT}:3000/tcp
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}